from keyboardLayouts import MACBOOK_TOP_CASE_KEYS, DELL_KB216_MAIN_KEYS


DETECTED_KEYBOARD = DELL_KB216_MAIN_KEYS

HAND_TASK_PATH = "src/hand_landmarker.task"
KEYBOARD_MODEL_PATH = "src/best.pt"
CAMERA_ID = 0
CONFIDENCE_REQ = 0.4
THRESHOLD = 5 * pow(10, -5)
FINGERTIP_HISTORY_SIZE = 5
KEY_HISTORY_SIZE = 8
MIN_PRESS_TRAVEL = 0.002
PRESS_COOLDOWN_MS = 150
SMOOTHING_ALPHA = 0.4
KEYBOARD_POINT_SMOOTHING_ALPHA = 0.35
MANUAL_CORNER_LABELS = (
    "top-left",
    "top-right",
    "bottom-right",
    "bottom-left",
)
MANUAL_CORNER_SHORT_LABELS = ("TL", "TR", "BR", "BL")
